# Task 1: Data Cleaning & Wrangling  
Dataset: (E-Commerce Sales Dataset)

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_excel("../data/dataset.xlsx")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,Adidas Sales Database,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
4,NaN,Foot Locker,1185732,2020-01-01 00:00:00,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000,0.5,In-store

## Step 2: Data Overview

In [15]:
df.shape

(9652, 14)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9652 entries, 0 to 9651
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   9649 non-null   object
 2   Unnamed: 2   9650 non-null   object
 3   Unnamed: 3   9649 non-null   object
 4   Unnamed: 4   9649 non-null   object
 5   Unnamed: 5   9649 non-null   object
 6   Unnamed: 6   9649 non-null   object
 7   Unnamed: 7   9649 non-null   object
 8   Unnamed: 8   9649 non-null   object
 9   Unnamed: 9   9649 non-null   object
 10  Unnamed: 10  9649 non-null   object
 11  Unnamed: 11  9649 non-null   object
 12  Unnamed: 12  9649 non-null   object
 13  Unnamed: 13  9649 non-null   object
dtypes: float64(1), object(13)
memory usage: 1.0+ MB

In [17]:
df.describe()

       Unnamed: 0
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

## Step 3: Check Missing Values

In [18]:
df.isnull().sum()

Unnamed: 0     9652
Unnamed: 1        3
Unnamed: 2        2
Unnamed: 3        3
Unnamed: 4        3
Unnamed: 5        3
Unnamed: 6        3
Unnamed: 7        3
Unnamed: 8        3
Unnamed: 9        3
Unnamed: 10       3
Unnamed: 11       3
Unnamed: 12       3
Unnamed: 13       3
dtype: int64

## Step 4: Data Cleaning  
Handling missing values, removing duplicates, and transforming data

In [19]:
df = df.drop_duplicates()

In [20]:
df.isnull().sum()

Unnamed: 0     9651
Unnamed: 1        2
Unnamed: 2        1
Unnamed: 3        2
Unnamed: 4        2
Unnamed: 5        2
Unnamed: 6        2
Unnamed: 7        2
Unnamed: 8        2
Unnamed: 9        2
Unnamed: 10       2
Unnamed: 11       2
Unnamed: 12       2
Unnamed: 13       2
dtype: int64

In [32]:
df['Invoice Date'] = pd.to_datetime(df['Invoice Date'])

In [33]:
df['Price per Unit'] = df['Price per Unit'].replace('[\$,]', '', regex=True).astype(float)
df['Total Sales'] = df['Total Sales'].replace('[\$,]', '', regex=True).astype(float)
df['Operating Profit'] = df['Operating Profit'].replace('[\$,]', '', regex=True).astype(float)

In [35]:
df['Operating Margin'] = df['Operating Margin'].replace('%', '', regex=True).astype(float)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        0 non-null      float64
 1   Retailer          9648 non-null   object
 2   Retailer ID       9648 non-null   int64
 3   Invoice Date      9648 non-null   datetime64[ns]
 4   Region            9648 non-null   object
 5   State             9648 non-null   object
 6   City              9648 non-null   object
 7   Product           9648 non-null   object
 8   Price per Unit    9648 non-null   float64
 9   Units Sold        9648 non-null   int64
 10  Total Sales       9648 non-null   float64
 11  Operating Profit  9648 non-null   float64
 12  Operating Margin  9648 non-null   float64
 13  Sales Method      9648 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(2), object(6)
memory usage: 1.0+ MB

In [37]:
df['Sales Method'] = df['Sales Method'].str.lower()

In [38]:
df.isnull().sum()

Unnamed: 0          9648
Retailer               0
Retailer ID            0
Invoice Date           0
Region                 0
State                  0
City                   0
Product                0
Price per Unit         0
Units Sold             0
Total Sales            0
Operating Profit       0
Operating Margin       0
Sales Method           0
dtype: int64

## Step 5: Final Cleaned Dataset  
Dataset is now ready for analysis

In [39]:
df.head()

,Unnamed: 0,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,NaN,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,in-store
1,NaN,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,in-store
2,NaN,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,in-store
3,NaN,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,in-store
4,NaN,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,in-store

In [40]:
df.to_csv("../output/cleaned_data.csv", index=False)